export const ADD_LOCATION = 'ADD_LOCATION'
export const REMOVE_LOCATION = 'REMOVE_LOCATION'
export const SET_LOCATION = 'SET_LOCATION'
export const GET_LOCATIONS = 'GET_LOCATIONS'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'
export const SET_CATEGORY = 'SET_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES'
